// Code generated by "stringer -type=stateInt"; DO NOT EDIT.

package polymers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UPDATE_CURRENT - -1]
	_ = x[NO_TRANSITION-1]
	_ = x[OBTAIN-2]
	_ = x[HAND-3]
	_ = x[TRADE-4]
	_ = x[COMPLETED-5]
}

const (
	_stateInt_name_0 = "UPDATE_CURRENT"
	_stateInt_name_1 = "NO_TRANSITIONOBTAINHANDTRADECOMPLETED"
)

var (
	_stateInt_index_1 = [...]uint8{0, 13, 19, 23, 28, 37}
)

func (i stateInt) String() string {
	switch {
	case i == -1:
		return _stateInt_name_0
	case 1 <= i && i <= 5:
		i -= 1
		return _stateInt_name_1[_stateInt_index_1[i]:_stateInt_index_1[i+1]]
	default:
		return "stateInt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
