// Code generated by "stringer -type=stateInt"; DO NOT EDIT.

package polymers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_TRANSITION-0]
	_ = x[OBTAIN-1]
	_ = x[HANDLE-2]
	_ = x[COMPLETED-3]
}

const _stateInt_name = "NO_TRANSITIONOBTAINHANDLECOMPLETED"

var _stateInt_index = [...]uint8{0, 13, 19, 25, 34}

func (i stateInt) String() string {
	if i < 0 || i >= stateInt(len(_stateInt_index)-1) {
		return "stateInt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _stateInt_name[_stateInt_index[i]:_stateInt_index[i+1]]
}
