// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Channel struct {
	ID   int64
	Name string
}

type ChannelSubscriber struct {
	ID        int64
	ChannelID int64
	UserID    int64
}

type Room struct {
	Name   string
	Engine string
}

type User struct {
	ID     int64
	Name   string
	Apikey string
	Room   sql.NullString
	Role   int64
}
