// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE
    id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByApikey = `-- name: GetUserByApikey :one
SELECT
    id, name, apikey, room, role
FROM
    users
WHERE
    apikey = ?
`

func (q *Queries) GetUserByApikey(ctx context.Context, apikey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByApikey, apikey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Apikey,
		&i.Room,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, name, apikey, room, role
FROM
    users
WHERE
    id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Apikey,
		&i.Room,
		&i.Role,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT
    id, name, apikey, room, role
FROM
    users
WHERE
    name = ?
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Apikey,
		&i.Room,
		&i.Role,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    id, name, apikey, room, role
FROM
    users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Apikey,
			&i.Room,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :one
INSERT INTO
    users (name, apikey, room, role)
VALUES
    (?, ?, ?, ?) RETURNING id, name, apikey, room, role
`

type InsertUserParams struct {
	Name   string
	Apikey string
	Room   sql.NullString
	Role   int64
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.Name,
		arg.Apikey,
		arg.Room,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Apikey,
		&i.Room,
		&i.Role,
	)
	return i, err
}

const patchUserRole = `-- name: PatchUserRole :one
UPDATE users
SET
    role = ?
WHERE
    name = ? RETURNING id, name, apikey, room, role
`

type PatchUserRoleParams struct {
	Role int64
	Name string
}

func (q *Queries) PatchUserRole(ctx context.Context, arg PatchUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, patchUserRole, arg.Role, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Apikey,
		&i.Room,
		&i.Role,
	)
	return i, err
}

const updateUserRoom = `-- name: UpdateUserRoom :exec
UPDATE users
SET
    room = ?
WHERE
    id = ?
`

type UpdateUserRoomParams struct {
	Room sql.NullString
	ID   int64
}

func (q *Queries) UpdateUserRoom(ctx context.Context, arg UpdateUserRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRoom, arg.Room, arg.ID)
	return err
}
