version: '3'

tasks:
  build:
    cmds:
      - go build -v .\\cmd\\tournament\\
  run:
    deps: [run:go, run:vue, watch]
  run:go:
    cmds:
      - go build -v .\\cmd\\tournament\\
      - .\\tournament.exe
  run:vue:
    dir: '.\\web'
    cmds:
      - npx vite -l info --clearScreen false
      # - echo 'hi'
    silent: true
  watch:
    desc: Watch tailwindcss
    dir: '.\\web'
    cmds:
      - npx -q tailwindcss -i .\\src\\assets\\main.css -o .\\src\\assets\\output.css -q --watch
  run:race:
    cmds:
      - go run -race .\\cmd\\tournament\\
