version: '3'

tasks:
  build:
    cmds:
      - go build -v .\\cmd\\tournament\\
  run:
    deps: [run:go, run:vue]
  run:go:
    cmds:
      - go build -v .\\cmd\\tournament\\
      - .\\tournament.exe
  run:vue:
    deps: [watch]
    dir: '.\\web'
    cmds:
      - npm run dev
    silent: true
  watch:
    desc: Watch tailwindcss
    dir: '.\\web'
    cmds:
      - npx tailwindcss -i .\\src\\assets\\main.css -o .\\src\\assets\\output.css --watch
  run:race:
    cmds:
      - go run -race .\\cmd\\tournament\\
