version: "3"

tasks:
  build:
    desc: build app for multiple systems
    cmds:
      - task: build:vue
      - task: build:go64
      - task: build:go32
  build:go64:
    cmds:
      - go build -o tournament_x64.exe .\\cmd\\tournament\\
    env:
      GOOS: windows
      GOARCH: amd64
  build:go32:
    cmds:
      - go build -o tournament_x32.exe .\\cmd\\tournament\\
    env:
      GOOS: windows
      GOARCH: 386
  run:
    deps: [run:go, run:vue, watch]
  run:go:
    cmds:
      - go run -v ./cmd/tournament/main.go
  run:vue:
    dir: '.\\web'
    cmds:
      - npx vite -l info --clearScreen false --host
      # - echo 'hi'
    silent: true
  build:vue:
    dir: '.\\web'
    cmds:
      - npm run build
  watch:
    desc: Watch tailwindcss
    dir: '.\\web'
    cmds:
      - npx -q tailwindcss -i .\\src\\assets\\main.css -o .\\src\\assets\\output.css -q --watch
  run:race:
    cmds:
      - go run -race .\\cmd\\tournament\\
