version: '3'

tasks:
  build:
    cmds:
      - go build -v .\\cmd\\tournament\\
  run:
    cmds:
      - go build -v .\\cmd\\tournament\\
      - .\\tournament.exe
  run:race:
    cmds:
      - go run -race .\\cmd\\tournament\\
