// Code generated by "stringer -type=EngineStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS_WAITING-0]
	_ = x[STATUS_STARTED-1]
	_ = x[STATUS_COMPLETED-2]
}

const _EngineStatus_name = "STATUS_WAITINGSTATUS_STARTEDSTATUS_COMPLETED"

var _EngineStatus_index = [...]uint8{0, 14, 28, 44}

func (i EngineStatus) String() string {
	if i < 0 || i >= EngineStatus(len(_EngineStatus_index)-1) {
		return "EngineStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineStatus_name[_EngineStatus_index[i]:_EngineStatus_index[i+1]]
}
