// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package hub

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNDEFINED - -1]
	_ = x[HUB_SUBSCRIBE-1]
	_ = x[HUB_NEW_ROOM-2]
}

const (
	_MessageType_name_0 = "UNDEFINED"
	_MessageType_name_1 = "HUB_SUBSCRIBEHUB_NEW_ROOM"
)

var (
	_MessageType_index_1 = [...]uint8{0, 13, 25}
)

func (i MessageType) String() string {
	switch {
	case i == -1:
		return _MessageType_name_0
	case 1 <= i && i <= 2:
		i -= 1
		return _MessageType_name_1[_MessageType_index_1[i]:_MessageType_index_1[i+1]]
	default:
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
