// Code generated by "stringer -type=Role"; DO NOT EDIT.

package hub

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[Admin_Role-1]
	_ = x[Judge_Role-2]
	_ = x[Player_Role-3]
}

const _Role_name = "NONEAdmin_RoleJudge_RolePlayer_Role"

var _Role_index = [...]uint8{0, 4, 14, 24, 35}

func (i Role) String() string {
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
